create table users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login    varchar(100) NOT NULL UNIQUE,
    password varchar      NOT NULL
);

create table locations
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_name varchar(100) not null,
    user_id       int,
    latitude      decimal,
    longitude     decimal,
    foreign key (user_id) references users (id)
);

create table sessions
(
    id         uuid PRIMARY KEY,
    user_id    int,
    expires_at timestamp,
    foreign key (user_id) references users (id)
)